# Generated by Django 4.1.3 on 2022-11-03 13:55

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя пользователя')),
                ('birth', models.DateField(verbose_name='Дата рождения')),
                ('login', models.CharField(max_length=24, unique=True)),
                ('password', models.CharField(max_length=24)),
                ('phone', phone_field.models.PhoneField(help_text='Введите номер телефона', max_length=31, unique=True)),
                ('tg', models.CharField(blank=True, help_text='Ваш никнейм в Telegram', max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
    ]
